spring:
  application:
    name: nbj-group-tenant-management
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/nbj_tenant_management
    username: ${DB_USERNAME:nbjuser}
    password: ${DB_PASSWORD:nbjpass123}
    driver-class-name: org.postgresql.Driver

  stripe:
    secret-key: sk_test_51SFFTo0JWONq8U474tzNLPALRnAdzIvtYlfiUlaPpCINzBJ4UADS1TNyKPwoRkKjaYfqjt14UAGaRiJRYTsci72F00J8jWZ7XJ
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_...} # We will get this later


  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  
  # SQL Initialization
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Application Configuration
app:
  jwt:
    secret: ${JWT_SECRET:TDh4L0E/RChHK0tiUGVTaFZtWXEzdDZ3OXokQyZGKUpATmNRZlRqV25acjR1N3ghQSVEKkctS2FQZFNnVWtYcA==}
    expiration: 86400000 # 24 hours in milliseconds
    refresh-expiration: 604800000 # 7 days in milliseconds
  
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
    max-size: 10485760 # 10MB in bytes
    allowed-types: jpg,jpeg,png,pdf,doc,docx
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

# Logging Configuration
logging:
  level:
    com.nbjgroup: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/nbj-group.log

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: INFO
    com.nbjgroup: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  sql:
    init:
      mode: never

logging:
  level:
    root: WARN
    com.nbjgroup: INFO
  file:
    name: /var/log/nbj-group/application.log

server:
  port: ${PORT:8080}
