package com.nbjgroup.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "properties")
public class Property {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String address;
    private String mapLink;
    private String managerOwnerName;
    private int numberOfUnits;

    // Removed @OneToMany(mappedBy = "property", cascade = CascadeType.ALL, orphanRemoval = true)
    // List<Tenant> tenants;

    // Getters and setters are generated by Lombok
}
